services:
  php:
    image: php:7.4-apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "2052:80"
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tpqinet_asm_uat2
      MYSQL_USER: tpqi
      MYSQL_PASSWORD: db@tpqi
    command: --sql-mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    ports:
      - "3308:3306"
    volumes:
      - mysql_data8:/var/lib/mysql
    restart: always

        

volumes:
  mysql_data8: